---
- hosts: all
  gather_facts: no
  vars_files: [ ../../nodes.yml ]
  tasks:
  - name:   Create VPNV4 Configuration
    template: src=./template/eigrp-config.j2 dest='desiredcfg/{{ inventory_hostname }}.igp.cfg'
