---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
  - ios_config:
      lines:
        - service timestamps debug uptime
        - service timestamps log uptime
        - service password-encryption
      save: yes
