#
# Get VRF information from Devices
# This can be used when running vrf or non vrf commands
#
---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
  - ios_command:
      commands:
        - "show run vrf | inc ^ip vrf "
    register: vrfvar
  - set_fact: vrf_var="{% set r = vrfvar.stdout_lines %}{{ r | regex_replace('ip vrf ') }}"
#  - debug: var="{{vrfvar.stdout_lines | regex_replace('ip vrf ') | to_json }}"
#    with_items: "{{ vrfvar | map('regex_search','\\,') | list | unique }}"

  - ios_command:
      commands:
        - "sho ip bgp vpnv4 vrf {{vrf_var}} | beg Network"
        - "sho ip bgp vpnv4 vrf {{vrf_var}} summary | beg Neighbor"
    register: bgproutesvrf
    when: vrf_var !=""
  - debug: var=bgproutesvrf
