#
# Get device state using NAPALM
#
---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
  - name: Get Napalm facts
    napalm_get_facts:
      hostname: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      dev_os: "{{ node_os }}"
      filter: ['facts', 'bgp_neighbors', 'interfaces']
    register: napalm_output
  - name: Save Napalm_Facts to YML files
    copy:
      content: "{{napalm_output|to_nice_yaml(indent=4)}}"
      dest: './NapalmFacts/NapalmFacts_{{napalm_hostname}}.yml'
