---
- hosts: all
  gather_facts: no
  vars_files: [ nodes.yml ]
  tasks:
  - name:   Create VPNV4 Configuration
    template: src=EIGRP/eigrp-config.j2 dest='EIGRP/config/{{ inventory_hostname }}-eigrp.cfg'
