#The Layer3 Infrastructure creation for the SIM router is not working yet
# code fix required

---
- hosts: all
  gather_facts: no
  vars_files: [ nodes.yml ]
  tasks:
  - name:   Create VPNV4 Configuration
    template: src=L3INF/interfaces-config.j2 dest='L3INF/config/{{ inventory_hostname }}l3inf.cfg'
