---
- hosts: all
  gather_facts: no
  vars_files: [ nodes.yml ]
  tasks:
  - name:   Create VPNV4 Configuration
    template: src=VPNV4/interfaces-config.j2 dest='VPNV4/config/{{ inventory_hostname }}vpnv4if.cfg'
