---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
  - ios_command:
      commands:
        - "show run | inc (ip vrf )[^forwarding]"
    register: vrfid
  - set_fact: vrf_id="{% set r = vrfid.stdout[0] %}{{ r | regex_replace('ip vrf ') }}"
  - debug: var=facts

  - name: Get VRF BGP Summary
    ios_command:
      commands:
       - "show ip bgp vpnv4 vrf {{vrf_id}} summary"
    register: BGPSum

  - name: Save Output BGP_Summary
    copy:
      content: "{{ BGPSum.stdout[0] }}"
      dest: './BGP_Summary/BGPSummary_{{ inventory_hostname }}.conf'
