---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
  - ios_command:
      commands:
        - "show run | inc (ip vrf )[^forwarding]"
    register: vrfid
  - debug: var=vrfid
  - set_fact: vrf_id="{% set r = vrfid.stdout[0] %}{{ r | regex_replace('ip vrf ') }}"
