#
# Get detailed BGP route report
#
---
- include: VRFCheck.yml
  name:    Get VRF Name

- hosts: all
  gather_facts: false
  connection: local

- hosts: all
  gather_facts: false
  connection: local
  name:  Show VRF BGP Routes
  tasks:
  - ios_command:
      commands:
        - "sho ip bgp vpnv4 vrf {{vrf_var}} | beg Network"
        - "sho ip bgp vpnv4 vrf {{vrf_var}} summary | beg Neighbor"
    register: bgproutesvrf
    when: vrf_var !=""
  - copy:
      content: "{{ bgproutesvrf.stdout[0] }}"
      dest: './BGP_Routes/BGPRoutes_{{ inventory_hostname }}.log'
    when: vrf_var !=""

- hosts: all
  gather_facts: false
  connection: local
  name:  Show BGP Routes
  tasks:
  - ios_command:
      commands:
        - "sho ip bgp | beg Network"
        - "sho ip bgp summary | beg Neighbor"
    register: bgproutes
    when: vrf_var ==""
#  - debug: var=bgproutes
  - copy:
      content: "{{ bgproutes.stdout[0] }}"
      dest: './BGP_Routes/BGPRoutes_{{ inventory_hostname }}.log'
    when: vrf_var ==""
