#
# Get device state using NAPALM
#
---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
  - name: Get Napalm facts
    napalm_get_facts:
      hostname: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      dev_os: "{{ node_os }}"
      filter: ['facts']
    register: napalm_facts
  - name: Print facts
    debug:
      msg: "{{ napalm_facts.ansible_facts|to_nice_json }}"
      tags: [print_action]
