---
- name:  Collect SNMP and vendor-specific facts from devices. Create a text report
  hosts: all
  vars:
  - results: results
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - file: path={{results}}/uptime.log state=touch
    run_once: true
  - snmp_facts:
      host: "{{ansible_host}}"
      version: v2
      community: cisco
  - ios_facts: provider={{ios_provider}}
  - lineinfile:
      dest:   "{{results}}/uptime.log"
      regexp: "{{inventory_hostname}}"
      line:   "{{'%20s %8s'|format(inventory_hostname,ansible_sysuptime)}}"
